# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.cache/wt [current_project]
set_property parent.project_path C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/design_project_DIP.bd
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_processing_system7_0_0/design_project_DIP_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_xbar_0/design_project_DIP_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/ip/design_project_DIP_auto_pc_0/design_project_DIP_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/design_project_DIP_ooc.xdc]
set_property is_locked true [get_files C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/design_project_DIP.bd]

read_vhdl -library xil_defaultlib C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/sources_1/bd/design_project_DIP/hdl/design_project_DIP_wrapper.vhd
read_xdc C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/constrs_1/new/stepper_DIP_const.xdc
set_property used_in_implementation false [get_files C:/Zynq_Book/project_stepper_DIP/project_stepper_DIP.srcs/constrs_1/new/stepper_DIP_const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_project_DIP_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_project_DIP_wrapper.dcp
catch { report_utilization -file design_project_DIP_wrapper_utilization_synth.rpt -pb design_project_DIP_wrapper_utilization_synth.pb }
