# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/stepper_DIP_const.xdc

# Block Designs: bd/design_project_DIP/design_project_DIP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP || ORIG_REF_NAME==design_project_DIP}]

# IP: bd/design_project_DIP/ip/design_project_DIP_processing_system7_0_0/design_project_DIP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_processing_system7_0_0 || ORIG_REF_NAME==design_project_DIP_processing_system7_0_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_0_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_0_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_1_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_1_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_2_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_2_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_processing_system7_0_axi_periph_0/design_project_DIP_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_project_DIP_processing_system7_0_axi_periph_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_xbar_0/design_project_DIP_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_xbar_0 || ORIG_REF_NAME==design_project_DIP_xbar_0}]

# IP: bd/design_project_DIP/ip/design_project_DIP_auto_pc_0/design_project_DIP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_auto_pc_0 || ORIG_REF_NAME==design_project_DIP_auto_pc_0}]

# XDC: bd/design_project_DIP/ip/design_project_DIP_processing_system7_0_0/design_project_DIP_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_processing_system7_0_0 || ORIG_REF_NAME==design_project_DIP_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_0_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_0_0/design_project_DIP_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_0_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_1_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_1_0/design_project_DIP_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_1_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_2_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0_ooc.xdc

# XDC: bd/design_project_DIP/ip/design_project_DIP_axi_gpio_2_0/design_project_DIP_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_project_DIP_axi_gpio_2_0 || ORIG_REF_NAME==design_project_DIP_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0}]

# XDC: bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_project_DIP_rst_processing_system7_0_100M_0}]

# XDC: bd/design_project_DIP/ip/design_project_DIP_rst_processing_system7_0_100M_0/design_project_DIP_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/design_project_DIP/ip/design_project_DIP_xbar_0/design_project_DIP_xbar_0_ooc.xdc

# XDC: bd/design_project_DIP/ip/design_project_DIP_auto_pc_0/design_project_DIP_auto_pc_0_ooc.xdc

# XDC: bd/design_project_DIP/design_project_DIP_ooc.xdc
